apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    app: backend-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
        - name: backend-feed
          image: babadee30/udagram-api-feed:v2
          imagePullPolicy: Always
          volumeMounts:
            - name: aws-secret
              mountPath: "/root/.aws/"
              readOnly: true 
          envFrom:
          - secretRef:
              name: udagram-secret
      volumes:
      - name: aws-secret
        secret:
          secretName: aws-secret