apiVersion: v1
kind: Service
metadata:
  labels:
    service: backend-feed-svc
  name: backend-feed-svc
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: backend-feed