apiVersion: v1
kind: Service
metadata:
  labels:
    service: backend-user-svc
  name: backend-user-svc
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: backend-user